### ISSUE TITLE
Antivirus triggered on install 

### ISSUE THREAD

**Issue by ImagineerNL** [ashupp/Streamdeck-vJoy#12]
My antivirus was triggered on this install.

I assume it is a false positive, but that's hard to verify.

Might help on confidence if it was listed on https://streamdeck-plugins.com/ or the internal streamdeck plugin page. (No idea how to handle that)

https://www.f-secure.com/v-descs/w32_malware.shtml

![Antivirus](https://user-images.githubusercontent.com/62603552/130803798-16364400-de5c-4db8-8be8-527486bf5523.jpg)

**Comment by ashupp** [comment]
Hello and thank you for your message and the provided information.

It seems to be related to your detection settings because in the screenshot the given reason is "Rare application" which is actually the fact and not a virus. So its not even a false positive... 
The fact that this is a rare application is obvious because of its speciality of purpose. 
Because of the speciality this app will also not be listed on official streamdeck store.

Please see also the virustotal report of the current plugin executable file.
[https://www.virustotal.com/gui/file/6b9d63d2a5d278487b304aed56aeb405a5187e84cbc878b1e052cad744ba1893/detection](https://www.virustotal.com/gui/file/6b9d63d2a5d278487b304aed56aeb405a5187e84cbc878b1e052cad744ba1893/detection)

I will close this issue. Thanks again and enjoy the app 👍🏻
